# ============================================================================
# .secrets.yaml - Secrets Configuration (DO NOT COMMIT TO GIT!)
# ============================================================================
# Place this in your project root and add to .gitignore
# Alternatively, use environment variables

default:
  token: "anova-your-token-here"

development:
  token: "anova-dev-token-here"

production:
  token: "anova-prod-token-here"